### ISSUE TITLE
[1.12.2] Black screen when stepping inside plonk rendered items

### ISSUE THREAD

**Issue by Landiie** [breakinblocks/Plonk#2] opened 2020-10-20 02:47 UTC
![ezgif com-gif-maker](https://user-images.githubusercontent.com/43101146/96534019-cc063600-1243-11eb-8929-3e2d62c08428.gif)
if you need anything from me, let me know! this is in a modpack so there might be some complications there. I havent tested this in a vanilla instance

**Comment by BlueAgent** [comment] 2020-10-21 14:19
Oops, 1.12.2 didn't override `isFullCube` like in 1.7.10.
Fixed in [Plonk v5.0.1 (mc 1.12.2)](https://www.curseforge.com/minecraft/mc-mods/plonk/files/3088601).

Bug fortunately only happens in 1.12.2.
There's a minor bug in 1.7.10 and 1.12.2 where the third person camera collides with the block, but not sure how to fix it... In 1.16.3 there's `RayTraceContext.VISUAL` / `getRayTraceShape` so the third person camera passes through as intended.

**Closed as completed by BlueAgent** 2020-10-21 14:19 UTC
Labels: bug, 1.12.2

**Comment by k1r0s** [comment] 2020-10-31 22:02
it damages you on survival, like suffocating damage.. :|

**Comment by BlueAgent** [comment] 2020-11-01 15:42
@k1r0s Does suffocation happen on the latest version of Plonk?

**Comment by k1r0s** [comment] 2020-11-01 21:42
didn't tested latest one so nvm, thanks!
